disabled_rules:
  - closure_body_length
  - cyclomatic_complexity
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - file_length
  - for_where
  - function_parameter_count
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - multiline_arguments_brackets # It's buggy and takes array args as being multi-args
  - multiline_literal_brackets # Same
  - multiline_parameters_brackets # Same
  - multiline_arguments # See https://github.com/realm/SwiftLint/issues/1896
  - multiline_function_chains
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - object_literal
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_string_enum_value
  - redundant_type_annotation
  - single_test_class
  - sorted_imports
  - strict_fileprivate # Enable in Swift 4
  - switch_case_on_newline
  - toggle_bool
  - trailing_comma
  - unused_enumerated
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
opt_in_rules:
  - custom_rules # Defined at the end of this file
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - colon
  - collection_alignment
  - convenience_type
  - comma
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_parameters
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_cast
  - force_unwrapping
  - force_try
  - function_body_length
  - function_default_parameter_at_end
  - identical_operands
  - identifier_name
  - joined_default_parameter
  - large_tuple
  - legacy_random
  - modifier_order
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - nslocalizedstring_key
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - override_in_extension
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - required_enum_case
  - sorted_first_last
  - statement_position
  - static_operator
  - strong_iboutlet
  - switch_case_alignment
  - todo
  - trailing_closure
  - trailing_newline
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_import
  - unused_private_declaration
  - untyped_error_in_catch
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - xct_specific_matcher
  - yoda_condition
identifier_name:
  min_length:
    warning: 2
type_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
large_tuple:
  warning: 3
  error: 4
function_body_length:
  - 50
number_separator:
  minimum_length: 5
  minimum_fraction_length: 100
nesting:
  type_level: 2
private_outlet:
  allow_private_set: true
superfluous_disable_command: warning
trailing_whitespace:
  ignores_empty_lines: true
attributes:
  always_on_line_above:
    - "@objc"
    - "@nonobjc"
    - "@available"
    - "@discardableResult"
  always_on_same_line:
    - "@IBOutlet"
    - "@IBAction"
    - "@NSManaged"
    - "@testable"

custom_rules:
  weak_timer:
    included: ".*.swift"
    name: "Weak Timer"
    regex: '\sTimer\.\w+\([\w\.]*\)[\n\r\s]\{[\n\r\s][^\[]'
    message: "Timer closures should use [weak self] to prevent retain cycles"
  weak_kvo:
    included: ".*.swift"
    name: "Weak KVO"
    regex: 'KVObserver\(.*\) \{ [^\[]'
    message: "KVO closures should use [weak self] to prevent retain cycles"
included:
  - AllTrails/
excluded:
  - AllTrails/Resources/